# Base Image
FROM ubuntu:18.04

# Update OS packages and install additional software
RUN apt -y update &&  apt install -y wget nginx software-properties-common apt-transport-https \
	&& wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb \
	&& dpkg -i packages-microsoft-prod.deb \
	&& add-apt-repository universe \
	&& apt -y update \
	&& apt install -y dotnet-sdk-3.0

# Configure Nginx environment
CMD service nginx start

# Configure Nginx environment
COPY ./default /etc/nginx/sites-available/default

# Configure work directory
WORKDIR /app

# Copy website code to container
COPY ./website/. .

# Configure network requirements
EXPOSE 80:8080

# Define the entry point of the process that runs in the container
ENTRYPOINT ["dotnet", "website.dll"]